dailyshop = {
    ListAvailable = {
        ["pvp_pack_2"] = {
            id = "pvp_pack_2",
            type = "items",
            label = "PvP Pack #2",
            Description = "Get 20x M60, 20x Special Carbine & 15x Kuruma for less than the shop price. Deal of the day!",
            price = 1950000,
            items = {
                {name = "weapon_combatmg", count = 20},
                {name = "weapon_specialcarbine", count = 20},
                {name = "kuruma", count = 15}
            },
            image = "weapon_combatmg",
        },
        ["pack_veh1"] = {
            id = "pack_veh1",
            type = "items",
            label = "Vehicle Pack #1",
            Description = "5x Kuruma, 5x Revolter",
            price = 120000,
            items = {
                {name = "revolter", count = 5},
                {name = "kuruma", count = 5}
            },
            image = "revolter",
        },
        ["ped_fitness"] = {
            id = "ped_fitness",
            type = "ped",
            label = "Fitness Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_fitness_02",
            price = 100000,
        },
        ["ped_fitness_2"] = {
            id = "ped_fitness_2",
            type = "ped",
            label = "Fitness Ped #2",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_fitness_01",
            price = 500000,
        },
        ["ped_import_1"] = {
            id = "ped_import_1",
            type = "ped",
            label = "Import Export Skin",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "g_f_importexport_01",
            price = 300000,
        },
        ["jus2peche"] = {
            id = "jus2peche",
            type = "ped",
            label = "Jus2Peche Skin",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_beach_01",
            price = 200000,
        },
        ["pandaped"] = {
            id = "pandaped",
            type = "ped",
            label = "MGZ Panda Skin",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_genhot_01",
            price = 100000,

        },
        ["beach_ped_2"] = {
            id = "beach_ped_2",
            type = "ped",
            label = "Beach Ped #2",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_topless_01",
            price = 120000,
        },
        ["soucent"] = {
            id = "soucent",
            type = "ped",
            label = "RSKV Skin",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_soucent_03",
            price = 150000,
        },
        ["yoga_ped"] = {
            id = "yoga_ped",
            type = "ped",
            label = "Yoga Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_yoga_01",
            price = 200000,
        },
        ["epsilon"] = {
            id = "epsilon",
            type = "ped",
            label = "Epsilon Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_epsilon_01",
            price = 100000,
        },
        ["eastsa"] = {
            id = "eastsa",
            type = "ped",
            label = "East SA Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_eastsa_03",
            price = 100000,
        },
        ["hiker_ped"] = {
            id = "hiker_ped",
            type = "ped",
            label = "Hiker Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_hiker_01",
            price = 100000,
        },
        ["hipie"] = {
            id = "hipie",
            type = "ped",
            label = "Hipie Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_hippie_01",
            price = 100000,
        },
        ["indian_ped"] = {
            id = "indian_ped",
            type = "ped",
            label = "Indian Ped",
            Description = "The mythical character is finally available! Be the first to own ",
            model = "a_f_y_indian_01",
            price = 100000,
        }
    },
    ActualShop = {}
}