SkinMakerConfig = {} 

SkinMakerConfig.defaultModel = "mp_m_freemode_01" 

SkinMakerConfig.defaultClothes = {
    torso = {
        id = 15,
        txt = 0
    }
}

SkinMakerConfig.listCharacters = {
    {model = "mp_m_freemode_01", role = "user"},
    {model = "mp_f_freemode_01", role = "user"},
    {model = "a_f_m_skidrow_01", role = "vip"},
    {model = "a_f_y_eastsa_03", role = "vip"},
    {model = "a_f_y_epsilon_01", role = "vip"},
    {model = "a_f_y_fitness_01", role = "vip"},
    {model = "a_f_y_fitness_02", role = "vip"},
    {model = "a_f_y_genhot_01", role = "vip"},
    {model = "a_f_y_golfer_01", role = "vip"},
    {model = "a_f_y_hiker_01", role = "vip"},
    {model = "a_f_y_hippie_01", role = "vip"},
    {model = "a_f_y_hipster_01", role = "vip"},
    {model = "a_f_y_indian_01", role = "vip"},
    {model = "a_f_y_juggalo_01", role = "vip"},
    {model = "a_f_y_runner_01", role = "vip"},
    {model = "a_f_y_rurmeth_01", role = "vip"},
    {model = "a_f_y_skater_01", role = "vip"},
    {model = "a_f_y_soucent_03", role = "vip"},
    {model = "a_f_y_topless_01", role = "vip"},
    {model = "a_f_y_tourist_01", role = "vip"},
    {model = "a_m_y_acult_02", role = "vip"},
    {model = "a_m_y_breakdance_01", role = "vip"},
    {model = "a_m_y_skater_01", role = "vip"},
    {model = "csb_stripper_02", role = "vip"},
    {model = "g_f_importexport_01", role = "vip"},
    {model = "g_f_y_ballas_01", role = "vip"},
    {model = "g_f_y_families_01", role = "vip"},
    {model = "g_f_y_lost_01", role = "vip"},
    {model = "g_f_y_vagos_01", role = "vip"},
    {model = "mp_f_cocaine_01", role = "vip"},
    {model = "mp_f_counterfeit_0", role = "vip"},
    {model = "mp_f_deadhooker", role = "vip"},
    {model = "mp_f_execpa_01", role = "vip"},
    {model = "mp_f_bennymech_01", role = "vip"},
    {model = "mp_f_helistaff_01", role = "vip"},
    {model = "mp_f_weed_01", role = "vip"},
    {model = "mp_m_exarmy_01", role = "vip"},
    {model = "s_f_y_cop_01", role = "vip"},
    {model = "s_f_y_scrubs_01", role = "vip"},
    {model = "s_f_y_sheriff_01", role = "vip"},
    {model = "s_f_y_sweatshop_01", role = "vip"},
    {model = "s_f_y_casino_01", role = "vip"},
    {model = "s_m_m_fibsec_01", role = "vip"},
    {model = "ig_amandatownley", role = "vip"},
    {model = "ig_maryann", role = "vip"},
    {model = "ig_old_man2", role = "vip"},
    {model = "ig_tracydisanto", role = "vip"},
    {model = "ig_tonya", role = "vip"},
    {model = "player_one", role = "vip"},
    {model = "player_two", role = "vip"},
    {model = "player_zero", role = "vip"},
    {model = "u_f_m_promourn_01", role = "vip"},
    {model = "u_f_m_corpse_01", role = "vip"},
    {model = "u_f_y_corpse_01", role = "vip"},
    {model = "u_f_y_corpse_02", role = "vip"},
    {model = "u_f_y_danceburl_01", role = "vip"},
    {model = "u_f_y_dancelthr_01", role = "vip"},
    {model = "u_f_y_dancerave_01", role = "vip"},
    {model = "u_m_m_jesus_01", role = "vip"},
    {model = "u_m_m_streetart_01", role = "vip"},
    {model = "u_m_y_baygor", role = "vip"},
    {model = "u_m_y_babyd", role = "vip"},
    {model = "u_m_y_mani", role = "vip"},
    {model = "u_m_y_pogo_01", role = "vip"},
    {model = "u_m_y_rsranger_01", role = "vip"},
    {model = "u_m_y_gabriel", role = "vip"},
    {model = "u_m_y_zombie_01", role = "vip"},
    {model = "a_f_m_ktown_01", role = "vip"},
    {model = "a_f_m_trampbeac_01", role = "vip"},
    {model = "a_f_y_eastsa_01", role = "vip"},
    {model = "g_m_y_famdnf_01", role = "vip"},
    {model = "mp_m_boatstaff_01", role = "vip"},
    {model = "mp_m_securoguard_01", role = "vip"},
    {model = "s_f_y_ranger_01", role = "vip"},
    {model = "s_m_m_ccrew_01", role = "vip"},
    {model = "ig_amandatownley", role = "vip"},
    {model = "ig_djtalaurelia", role = "vip"},
    {model = "ig_jewelass", role = "vip"},
    {model = "u_f_m_miranda", role = "vip"},
    {model = "u_f_y_bikerchic", role = "vip"},
    {model = "u_f_y_poppymich", role = "vip"},
    {model = "u_f_y_lauren", role = "vip"},
    {model = "u_m_y_corpse_01", role = "vip"},
    {model = "u_m_m_blane", role = "vip"},
    {model = "u_m_y_danceburl_01", role = "vip"},
    {model = "u_f_y_taylor", role = "vip"},
    {model = "a_f_y_carclub_01", role = "vip"},
    {model = "a_f_y_beach_01", role = "vip"},
    {model = "a_f_m_beach_01", role = "vip"},
    {model = "a_f_m_fatcult_01", role = "vip"},
    {model = "a_f_y_vinewood_02", role = "vip"},
    {model = "s_f_y_clubbar_01", role = "vip"},
}