CountryFlag = {
    -- Europe
    ["AD"] = "🇦🇩", -- Andorre
    ["AL"] = "🇦🇱", -- Albanie
    ["AT"] = "🇦🇹", -- Autriche
    ["BA"] = "🇧🇦", -- Bosnie-Herzégovine
    ["BE"] = "🇧🇪", -- Belgique
    ["BG"] = "🇧🇬", -- Bulgarie
    ["BY"] = "🇧🇾", -- Biélorussie
    ["CH"] = "🇨🇭", -- Suisse
    ["CY"] = "🇨🇾", -- Chypre
    ["CZ"] = "🇨🇿", -- République tchèque
    ["DE"] = "🇩🇪", -- Allemagne
    ["DK"] = "🇩🇰", -- Danemark
    ["EE"] = "🇪🇪", -- Estonie
    ["ES"] = "🇪🇸", -- Espagne
    ["FI"] = "🇫🇮", -- Finlande
    ["FR"] = "🇫🇷", -- France
    ["GB"] = "🇬🇧", -- Royaume-Uni
    ["GR"] = "🇬🇷", -- Grèce
    ["HR"] = "🇭🇷", -- Croatie
    ["HU"] = "🇭🇺", -- Hongrie
    ["IE"] = "🇮🇪", -- Irlande
    ["IS"] = "🇮🇸", -- Islande
    ["IT"] = "🇮🇹", -- Italie
    ["LI"] = "🇱🇮", -- Liechtenstein
    ["LT"] = "🇱🇹", -- Lituanie
    ["LU"] = "🇱🇺", -- Luxembourg
    ["LV"] = "🇱🇻", -- Lettonie
    ["MC"] = "🇲🇨", -- Monaco
    ["MD"] = "🇲🇩", -- Moldavie
    ["ME"] = "🇲🇪", -- Monténégro
    ["MK"] = "🇲🇰", -- Macédoine du Nord
    ["MT"] = "🇲🇹", -- Malte
    ["NL"] = "🇳🇱", -- Pays-Bas
    ["NO"] = "🇳🇴", -- Norvège
    ["PL"] = "🇵🇱", -- Pologne
    ["PT"] = "🇵🇹", -- Portugal
    ["RO"] = "🇷🇴", -- Roumanie
    ["RS"] = "🇷🇸", -- Serbie
    ["RU"] = "🇷🇺", -- Russie
    ["SE"] = "🇸🇪", -- Suède
    ["SI"] = "🇸🇮", -- Slovénie
    ["SK"] = "🇸🇰", -- Slovaquie
    ["SM"] = "🇸🇲", -- Saint-Marin
    ["UA"] = "🇺🇦", -- Ukraine
    ["VA"] = "🇻🇦", -- Vatican

    -- Amérique du Nord
    ["AG"] = "🇦🇬", -- Antigua-et-Barbuda
    ["BB"] = "🇧🇧", -- Barbade
    ["BS"] = "🇧🇸", -- Bahamas
    ["BZ"] = "🇧🇿", -- Belize
    ["CA"] = "🇨🇦", -- Canada
    ["CR"] = "🇨🇷", -- Costa Rica
    ["CU"] = "🇨🇺", -- Cuba
    ["DM"] = "🇩🇲", -- Dominique
    ["DO"] = "🇩🇴", -- République dominicaine
    ["GD"] = "🇬🇩", -- Grenade
    ["GT"] = "🇬��", -- Guatemala
    ["HN"] = "🇭🇳", -- Honduras
    ["HT"] = "🇭🇹", -- Haïti
    ["JM"] = "🇯🇲", -- Jamaïque
    ["KN"] = "🇰🇳", -- Saint-Kitts-et-Nevis
    ["LC"] = "🇱🇨", -- Sainte-Lucie
    ["MX"] = "🇲🇽", -- Mexique
    ["NI"] = "🇳🇮", -- Nicaragua
    ["PA"] = "🇵🇦", -- Panama
    ["SV"] = "🇸🇻", -- Salvador
    ["TT"] = "🇹🇹", -- Trinité-et-Tobago
    ["US"] = "🇺🇸", -- États-Unis
    ["VC"] = "🇻🇨", -- Saint-Vincent-et-les-Grenadines

    -- Amérique du Sud
    ["AR"] = "🇦🇷", -- Argentine
    ["BO"] = "🇧🇴", -- Bolivie
    ["BR"] = "🇧🇷", -- Brésil
    ["CL"] = "🇨🇱", -- Chili
    ["CO"] = "🇨🇴", -- Colombie
    ["EC"] = "🇪🇨", -- Équateur
    ["GY"] = "🇬🇾", -- Guyana
    ["PE"] = "🇵🇪", -- Pérou
    ["PY"] = "🇵🇾", -- Paraguay
    ["SR"] = "🇸🇷", -- Suriname
    ["UY"] = "🇺🇾", -- Uruguay
    ["VE"] = "🇻🇪", -- Venezuela

    -- Asie
    ["AE"] = "🇦🇪", -- Émirats arabes unis
    ["AF"] = "🇦🇫", -- Afghanistan
    ["AM"] = "🇦🇲", -- Arménie
    ["AZ"] = "🇦🇿", -- Azerbaïdjan
    ["BD"] = "🇧🇩", -- Bangladesh
    ["BH"] = "🇧🇭", -- Bahreïn
    ["BN"] = "🇧🇳", -- Brunei
    ["BT"] = "🇧🇹", -- Bhoutan
    ["CN"] = "🇨🇳", -- Chine
    ["GE"] = "🇬🇪", -- Géorgie
    ["ID"] = "🇮🇩", -- Indonésie
    ["IL"] = "🇮🇱", -- Israël
    ["IN"] = "🇮🇳", -- Inde
    ["IQ"] = "🇮🇶", -- Irak
    ["IR"] = "🇮🇷", -- Iran
    ["JO"] = "🇯🇴", -- Jordanie
    ["JP"] = "🇯🇵", -- Japon
    ["KG"] = "🇰🇬", -- Kirghizistan
    ["KH"] = "🇰🇭", -- Cambodge
    ["KP"] = "🇰🇵", -- Corée du Nord
    ["KR"] = "🇰🇷", -- Corée du Sud
    ["KW"] = "🇰🇼", -- Koweït
    ["KZ"] = "🇰🇿", -- Kazakhstan
    ["LA"] = "🇱🇦", -- Laos
    ["LB"] = "🇱🇧", -- Liban
    ["LK"] = "🇱🇰", -- Sri Lanka
    ["MM"] = "🇲🇲", -- Myanmar (Birmanie)
    ["MN"] = "🇲🇳", -- Mongolie
    ["MV"] = "🇲🇻", -- Maldives
    ["MY"] = "🇲🇾", -- Malaisie
    ["NP"] = "🇳🇵", -- Népal
    ["OM"] = "🇴🇲", -- Oman
    ["PH"] = "🇵🇭", -- Philippines
    ["PK"] = "🇵🇰", -- Pakistan
    ["PS"] = "🇵🇸", -- Palestine
    ["QA"] = "🇶🇦", -- Qatar
    ["SA"] = "🇸🇦", -- Arabie saoudite
    ["SG"] = "🇸🇬", -- Singapour
    ["SY"] = "🇸🇾", -- Syrie
    ["TH"] = "🇹🇭", -- Thaïlande
    ["TJ"] = "🇹🇯", -- Tadjikistan
    ["TL"] = "🇹🇱", -- Timor oriental
    ["TM"] = "🇹🇲", -- Turkménistan
    ["TR"] = "🇹🇷", -- Turquie
    ["TW"] = "🇹🇼", -- Taïwan
    ["UZ"] = "🇺🇿", -- Ouzbékistan
    ["VN"] = "🇻🇳", -- Vietnam
    ["YE"] = "🇾🇪", -- Yémen

    -- Afrique
    ["AO"] = "🇦🇴", -- Angola
    ["BF"] = "🇧🇫", -- Burkina Faso
    ["BI"] = "🇧🇮", -- Burundi
    ["BJ"] = "🇧🇯", -- Bénin
    ["BW"] = "🇧🇼", -- Botswana
    ["CD"] = "🇨🇩", -- République démocratique du Congo
    ["CF"] = "🇨🇫", -- République centrafricaine
    ["CG"] = "🇨🇬", -- République du Congo
    ["CI"] = "🇨🇮", -- Côte d'Ivoire
    ["CM"] = "🇨🇲", -- Cameroun
    ["CV"] = "🇨🇻", -- Cap-Vert
    ["DJ"] = "🇩🇯", -- Djibouti
    ["DZ"] = "🇩🇿", -- Algérie
    ["EG"] = "🇪🇬", -- Égypte
    ["ER"] = "🇪🇷", -- Érythrée
    ["ET"] = "🇪🇹", -- Éthiopie
    ["GA"] = "🇬🇦", -- Gabon
    ["GH"] = "🇬🇭", -- Ghana
    ["GM"] = "🇬🇲", -- Gambie
    ["GN"] = "🇬🇳", -- Guinée
    ["GQ"] = "🇬🇶", -- Guinée équatoriale
    ["GW"] = "🇬🇼", -- Guinée-Bissau
    ["KE"] = "🇰🇪", -- Kenya
    ["KM"] = "🇰🇲", -- Comores
    ["LR"] = "🇱🇷", -- Liberia
    ["LS"] = "🇱🇸", -- Lesotho
    ["LY"] = "🇱🇾", -- Libye
    ["MA"] = "🇲🇦", -- Maroc
    ["MG"] = "🇲🇬", -- Madagascar
    ["ML"] = "🇲🇱", -- Mali
    ["MR"] = "🇲🇷", -- Mauritanie
    ["MU"] = "🇲🇺", -- Maurice
    ["MW"] = "🇲🇼", -- Malawi
    ["MZ"] = "🇲🇿", -- Mozambique
    ["NA"] = "🇳🇦", -- Namibie
    ["NE"] = "🇳🇪", -- Niger
    ["NG"] = "🇳🇬", -- Nigeria
    ["RW"] = "🇷🇼", -- Rwanda
    ["SC"] = "🇸🇨", -- Seychelles
    ["SD"] = "🇸🇩", -- Soudan
    ["SL"] = "🇸🇱", -- Sierra Leone
    ["SN"] = "🇸🇳", -- Sénégal
    ["SO"] = "🇸🇴", -- Somalie
    ["SS"] = "🇸🇸", -- Soudan du Sud
    ["ST"] = "🇸🇹", -- Sao Tomé-et-Principe
    ["SZ"] = "🇸🇿", -- Eswatini (Swaziland)
    ["TD"] = "🇹🇩", -- Tchad
    ["TG"] = "🇹🇬", -- Togo
    ["TN"] = "🇹🇳", -- Tunisie
    ["TZ"] = "🇹🇿", -- Tanzanie
    ["UG"] = "🇺🇬", -- Ouganda
    ["ZA"] = "🇿🇦", -- Afrique du Sud
    ["ZM"] = "🇿🇲", -- Zambie
    ["ZW"] = "🇿🇼", -- Zimbabwe

    -- Océanie
    ["AU"] = "🇦🇺", -- Australie
    ["FJ"] = "🇫🇯", -- Fidji
    ["FM"] = "🇫🇲", -- Micronésie
    ["KI"] = "🇰🇮", -- Kiribati
    ["MH"] = "🇲🇭", -- Îles Marshall
    ["NR"] = "🇳🇷", -- Nauru
    ["NZ"] = "🇳🇿", -- Nouvelle-Zélande
    ["PG"] = "🇵🇬", -- Papouasie-Nouvelle-Guinée
    ["PW"] = "🇵🇼", -- Palaos
    ["SB"] = "🇸🇧", -- Îles Salomon
    ["TO"] = "🇹🇴", -- Tonga
    ["TV"] = "🇹🇻", -- Tuvalu
    ["VU"] = "🇻🇺", -- Vanuatu
    ["WS"] = "🇼🇸", -- Samoa

    -- Territoires et dépendances
    ["AW"] = "🇦🇼", -- Aruba
    ["BL"] = "🇧🇱", -- Saint-Barthélemy
    ["BM"] = "🇧🇲", -- Bermudes
    ["BQ"] = "🇧🇶", -- Bonaire, Saint-Eustache et Saba
    ["CW"] = "🇨🇼", -- Curaçao
    ["FK"] = "🇫🇰", -- Îles Malouines
    ["GF"] = "🇬🇫", -- Guyane française
    ["GG"] = "🇬🇬", -- Guernesey
    ["GI"] = "🇬🇮", -- Gibraltar
    ["GL"] = "🇬🇱", -- Groenland
    ["GP"] = "🇬🇵", -- Guadeloupe
    ["GU"] = "🇬🇺", -- Guam
    ["HK"] = "🇭🇰", -- Hong Kong
    ["IM"] = "🇮🇲", -- Île de Man
    ["JE"] = "🇯🇪", -- Jersey
    ["MF"] = "🇲🇫", -- Saint-Martin
    ["MO"] = "🇲🇴", -- Macao
    ["MP"] = "🇲🇵", -- Îles Mariannes du Nord
    ["MQ"] = "🇲🇶", -- Martinique
    ["MS"] = "🇲🇸", -- Montserrat
    ["NC"] = "🇳🇨", -- Nouvelle-Calédonie
    ["PF"] = "🇵🇫", -- Polynésie française
    ["PM"] = "🇵🇲", -- Saint-Pierre-et-Miquelon
    ["PR"] = "🇵🇷", -- Porto Rico
    ["RE"] = "🇷🇪", -- La Réunion
    ["SH"] = "🇸🇭", -- Sainte-Hélène
    ["SJ"] = "🇸🇯", -- Svalbard et Jan Mayen
    ["SX"] = "🇸🇽", -- Saint-Martin (partie néerlandaise)
    ["TC"] = "🇹🇨", -- Îles Turques-et-Caïques
    ["TF"] = "🇹🇫", -- Terres australes et antarctiques françaises
    ["VI"] = "🇻🇮", -- Îles Vierges américaines
    ["VG"] = "🇻🇬", -- Îles Vierges britanniques
    ["WF"] = "🇼🇫", -- Wallis-et-Futuna
    ["YT"] = "🇾🇹", -- Mayotte
}