WeaponsAttachments = {
    [`weapon_specialcarbine`] = {
        itemName = "weapon_specialcarbine",
        Name = "Special Carbine",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_SPECIALCARBINE_CLIP_02`},
            [2] = {Name = "Drum Magazine", Hash = `COMPONENT_SPECIALCARBINE_CLIP_03`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM`},
            [5] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP_02`},
            [6] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [7] = {Name = "Etched Gun Metal Finish", Hash = `COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER`},
        },
    },
    [`weapon_specialcarbine_mk2`] = {
        itemName = "weapon_specialcarbine_mk2",
        Name = "Special Carbine MK2",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_SPECIALCARBINE_MK2_CLIP_02`},
            [2] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [3] = {Name = "Holographic Sight", Hash = `COMPONENT_AT_SIGHTS`},
            [4] = {Name = "Small Scope", Hash = `COMPONENT_AT_SCOPE_MACRO_MK2`},
            [5] = {Name = "Large Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM_MK2`},
            [6] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP_02`},
            [7] = {Name = "Flat Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_01`},
            [8] = {Name = "Tactical Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_02`},
            [9] = {Name = "Fat-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_03`},
            [10] = {Name = "Precision Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_04`},
            [11] = {Name = "Heavy Duty Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_05`},
            [12] = {Name = "Slanted Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_06`},
            [13] = {Name = "Split-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_07`},
            [14] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP_02`},
            [15] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_SC_BARREL_02`},
            [16] = {Name = "Digital Camo", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO`},
            [17] = {Name = "Brushstroke Camo", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_02`},
            [18] = {Name = "Woodland Camo", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_03`},
            [19] = {Name = "Skull", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_04`},
            [20] = {Name = "Sessanta Nove", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_05`},
            [21] = {Name = "Perseus", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_06`},
            [22] = {Name = "Leopard", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_07`},
            [23] = {Name = "Zebra", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_08`},
            [24] = {Name = "Geometric", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_09`},
            [25] = {Name = "Boom!", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_10`},
            [26] = {Name = "Patriotic", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01`},
            [27] = {Name = "Patriotic 2", Hash = `COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_02`},
            
        },
    },
    [`WEAPON_ASSAULTRIFLE`] = {
        itemName = "WEAPON_ASSAULTRIFLE",
        Name = "Assault Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_ASSAULTRIFLE_CLIP_02`},
            [2] = {Name = "Drum Magazine", Hash = `COMPONENT_ASSAULTRIFLE_CLIP_03`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_MACRO`},
            [5] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP_02`},
            [6] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [7] = {Name = "Yusuf Amir Luxury Finish", Hash = `COMPONENT_ASSAULTRIFLE_VARMOD_LUXE`},
        },
    },
    [`WEAPON_ASSAULTRIFLE_MK2`] = {
        itemName = "WEAPON_ASSAULTRIFLE_MK2",
        Name = "Assault Rifle MK 2",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CLIP_02`},
            [2] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP_02`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Holographic Sight", Hash = `COMPONENT_AT_SIGHTS`},
            [5] = {Name = "Small Scope", Hash = `COMPONENT_AT_SCOPE_MACRO_MK2`},
            [6] = {Name = "Large Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM_MK2`},
            [7] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP_02`},
            [8] = {Name = "Flat Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_01`},
            [9] = {Name = "Tactical Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_02`},
            [10] = {Name = "Fat-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_03`},
            [11] = {Name = "Precision Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_04`},
            [12] = {Name = "Heavy Duty Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_05`},
            [13] = {Name = "Slanted Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_06`},
            [14] = {Name = "Split-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_07`},
            [15] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_AR_BARREL_02`},
            [16] = {Name = "Digital Camo", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO`},
            [17] = {Name = "Brushstroke Camo", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_02`},
            [18] = {Name = "Woodland Camo", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_03`},
            [19] = {Name = "Skull", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_04`},
            [20] = {Name = "Sessanta Nove", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_05`},
            [21] = {Name = "Perseus", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_06`},
            [22] = {Name = "Leopard", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_07`},
            [23] = {Name = "Zebra", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_08`},
            [24] = {Name = "Geometric", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_09`},
            [25] = {Name = "Boom!", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_10`},
            [26] = {Name = "Patriotic", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01`},
            [27] = {Name = "Patriotic 2", Hash = `COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_02`},            
        },
    },
    [`weapon_carbinerifle_mk2`] = {
        itemName = "weapon_carbinerifle_mk2",
        Name = "Carbine Rifle MK2",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_CARBINERIFLE_MK2_CLIP_02`},
            [2] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP_02`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Holographic Sight", Hash = `COMPONENT_AT_SIGHTS`},
            [5] = {Name = "Small Scope", Hash = `COMPONENT_AT_SCOPE_MACRO_MK2`},
            [6] = {Name = "Large Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM_MK2`},
            [7] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [8] = {Name = "Flat Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_01`},
            [9] = {Name = "Tactical Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_02`},
            [10] = {Name = "Fat-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_03`},
            [11] = {Name = "Precision Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_04`},
            [12] = {Name = "Heavy Duty Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_05`},
            [13] = {Name = "Slanted Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_06`},
            [14] = {Name = "Split-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_07`},
            [15] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_CR_BARREL_02`},
            [16] = {Name = "Digital Camo", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO`},
            [17] = {Name = "Brushstroke Camo", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_02`},
            [18] = {Name = "Woodland Camo", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_03`},
            [19] = {Name = "Skull", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_04`},
            [20] = {Name = "Sessanta Nove", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_05`},
            [21] = {Name = "Perseus", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_06`},
            [22] = {Name = "Leopard", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_07`},
            [23] = {Name = "Zebra", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_08`},
            [24] = {Name = "Geometric", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_09`},
            [25] = {Name = "Boom!", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_10`},
            [26] = {Name = "Patriotic", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01`},
            [27] = {Name = "Patriotic 2", Hash = `COMPONENT_CARBINERIFLE_MK2_CAMO_IND_02`},            
        },
    },
    [`weapon_carbinerifle`] = {
        itemName = "weapon_carbinerifle",
        Name = "Carbine Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_CARBINERIFLE_CLIP_02`},
            [2] = {Name = "Box Magazine", Hash = `COMPONENT_CARBINERIFLE_CLIP_03`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM`},
            [5] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [6] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [7] = {Name = "Yusuf Amir Luxury Finish", Hash = `COMPONENT_CARBINERIFLE_VARMOD_LUXE`},
        },
    },
    [`weapon_bullpupshotgun`] = {
        itemName = "weapon_bullpupshotgun",
        Name = "Bullpup Shotgun",
        Components = {
            [1] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [2] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP_02`},
            [3] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
        },
    },
    [`weapon_combatpdw`] = {
        itemName = "weapon_combatpdw",
        Name = "Combat PDW", 
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_COMBATPDW_CLIP_02`},
            [2] = {Name = "Drum Magazine", Hash = `COMPONENT_COMBATPDW_CLIP_03`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [5] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_SMALL`},
        },
    },
    [`weapon_minismg`] = {
        itemName = "weapon_minismg",
        Name = "Mini Smg",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_MINISMG_CLIP_02`},
        },
    },
    [`weapon_advancedrifle`] = {
        itemName = "weapon_advancedrifle",
        Name = "Advanced Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_ADVANCEDRIFLE_CLIP_02`},
            [2] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [3] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_SMALL`},
            [4] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [5] = {Name = "Gilded Gun Metal Finish", Hash = `COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE`},
        },
    },
    [`weapon_bullpuprifle`] = {
        itemName = "weapon_bullpuprifle",
        Name = "Bullpup Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_BULLPUPRIFLE_CLIP_02`},
            [2] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [3] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_SMALL`},
            [4] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [5] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [6] = {Name = "Gilded Gun Metal Finish", Hash = `COMPONENT_BULLPUPRIFLE_VARMOD_LOW`},
        },
    },
    [`weapon_bullpuprifle_mk2`] = {
        itemName = "weapon_bullpuprifle_mk2",
        Name = "Bullpup Rifle MK2",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CLIP_02`},
            [2] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [3] = {Name = "Holographic Sight", Hash = `COMPONENT_AT_SIGHTS`},
            [4] = {Name = "Small Scope", Hash = `COMPONENT_AT_SCOPE_MACRO_02_MK2`},
            [5] = {Name = "Medium Scope", Hash = `COMPONENT_AT_SCOPE_SMALL_MK2`},
            [6] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_BP_BARREL_02`},
            [7] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [8] = {Name = "Flat Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_01`},
            [9] = {Name = "Tactical Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_02`},
            [10] = {Name = "Fat-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_03`},
            [11] = {Name = "Precision Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_04`},
            [12] = {Name = "Heavy Duty Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_05`},
            [13] = {Name = "Slanted Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_06`},
            [14] = {Name = "Split-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_07`},
            [15] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP_02`},
            [16] = {Name = "Digital Camo", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO`},
            [17] = {Name = "Brushstroke Camo", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_02`},
            [18] = {Name = "Woodland Camo", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_03`},
            [19] = {Name = "Skull", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_04`},
            [20] = {Name = "Sessanta Nove", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_05`},
            [21] = {Name = "Perseus", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_06`},
            [22] = {Name = "Leopard", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_07`},
            [23] = {Name = "Zebra", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_08`},
            [24] = {Name = "Geometric", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_09`},
            [25] = {Name = "Boom!", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_10`},
            [26] = {Name = "Patriotic", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01`},
            [27] = {Name = "Patriotic 2", Hash = `COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_02`},            
        },
    },
    [`weapon_compactrifle`] = {
        itemName = "weapon_compactrifle",
        Name = "Compact Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_COMPACTRIFLE_CLIP_02`},
            [2] = {Name = "Drum Magazine", Hash = `COMPONENT_COMPACTRIFLE_CLIP_03`},
        },
    },
    [`weapon_militaryrifle`] = {
        itemName = "weapon_militaryrifle",
        Name = "Military Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_MILITARYRIFLE_CLIP_02`},
            [2] = {Name = "Iron Sights", Hash = `COMPONENT_MILITARYRIFLE_SIGHT_01`},
            [3] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_SMALL`},
            [4] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [5] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
        },
    },
    [`weapon_combatmg`] = {
        itemName = "weapon_combatmg",
        Name = "M60",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_COMBATMG_CLIP_02`},
            [2] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM`},
            [3] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [4] = {Name = "Etched Gun Metal Finish", Hash = `COMPONENT_COMBATMG_VARMOD_LOWRIDER`},
        },  
    },
    [`weapon_combatmg_mk2`] = {
        itemName = "weapon_combatmg_mk2",
        Name = "M60 Mk II",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_COMBATMG_MK2_CLIP_02`},
            [2] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP_02`},
            [3] = {Name = "Holographic Sight", Hash = `COMPONENT_AT_SIGHTS`},
            [4] = {Name = "Medium Scope", Hash = `COMPONENT_AT_SCOPE_SMALL_MK2`},
            [5] = {Name = "Large Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM_MK2`},
            [6] = {Name = "Flat Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_01`},
            [7] = {Name = "Tactical Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_02`},
            [8] = {Name = "Fat-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_03`},
            [9] = {Name = "Precision Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_04`},
            [10] = {Name = "Heavy Duty Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_05`},
            [11] = {Name = "Slanted Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_06`},
            [12] = {Name = "Split-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_07`},
            [13] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_MG_BARREL_02`},
            [14] = {Name = "Digital Camo", Hash = `COMPONENT_COMBATMG_MK2_CAMO`},
            [15] = {Name = "Brushstroke Camo", Hash = `COMPONENT_COMBATMG_MK2_CAMO_02`},
            [16] = {Name = "Woodland Camo", Hash = `COMPONENT_COMBATMG_MK2_CAMO_03`},
            [17] = {Name = "Skull", Hash = `COMPONENT_COMBATMG_MK2_CAMO_04`},
            [18] = {Name = "Sessanta Nove", Hash = `COMPONENT_COMBATMG_MK2_CAMO_05`},
            [19] = {Name = "Perseus", Hash = `COMPONENT_COMBATMG_MK2_CAMO_06`},
            [20] = {Name = "Leopard", Hash = `COMPONENT_COMBATMG_MK2_CAMO_07`},
            [21] = {Name = "Zebra", Hash = `COMPONENT_COMBATMG_MK2_CAMO_08`},
            [22] = {Name = "Geometric", Hash = `COMPONENT_COMBATMG_MK2_CAMO_09`},
            [23] = {Name = "Boom!", Hash = `COMPONENT_COMBATMG_MK2_CAMO_10`},
            [24] = {Name = "Patriotic", Hash = `COMPONENT_COMBATMG_MK2_CAMO_IND_01`},
            [25] = {Name = "Patriotic 2", Hash = `COMPONENT_COMBATMG_MK2_CAMO_IND_02`},            
        },
    },
    [`weapon_heavysniper`] = {
        itemName = "weapon_heavysniper",
        Name = "AWP",
        Components = {
            [1] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_LARGE`},
            [2] = {Name = "Advanced Scope", Hash = `COMPONENT_AT_SCOPE_MAX`},
        },
    },
    [`weapon_heavysniper_mk2`] = {
        itemName = "weapon_heavysniper_mk2",
        Name = "AWP Mk II",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_HEAVYSNIPER_MK2_CLIP_02`},
            [2] = {Name = "Zoom Scope", Hash = `COMPONENT_AT_SCOPE_LARGE_MK2`},
            [3] = {Name = "Advanced Scope", Hash = `COMPONENT_AT_SCOPE_MAX`},
            [4] = {Name = "Night Vision Scope", Hash = `COMPONENT_AT_SCOPE_NV`},
            [5] = {Name = "Thermal Scope", Hash = `COMPONENT_AT_SCOPE_THERMAL`},
            [6] = {Name = "Suppressor", Hash = `COMPONENT_AT_SR_SUPP_03`},
            [7] = {Name = "Squared Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_08`},
            [8] = {Name = "Bell-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_09`},
            [9] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_SR_BARREL_02`},
            [10] = {Name = "Digital Camo", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO`},
            [11] = {Name = "Brushstroke Camo", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_02`},
            [12] = {Name = "Woodland Camo", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_03`},
            [13] = {Name = "Skull", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_04`},
            [14] = {Name = "Sessanta Nove", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_05`},
            [15] = {Name = "Perseus", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_06`},
            [16] = {Name = "Leopard", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_07`},
            [17] = {Name = "Zebra", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_08`},
            [18] = {Name = "Geometric", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_09`},
            [19] = {Name = "Boom!", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_10`},
            [20] = {Name = "Patriotic", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01`},
            [21] = {Name = "Patriotic 2", Hash = `COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_02`},            
        },
    },
    [`weapon_marksmanrifle`] = {
        itemName = "weapon_marksmanrifle",
        Name = "Marksman Rifle",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_MARKSMANRIFLE_CLIP_02`},
            [2] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM`},
            [3] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [4] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [5] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP`},
            [6] = {Name = "Yusuf Amir Luxury Finish", Hash = `COMPONENT_MARKSMANRIFLE_VARMOD_LUXE`},
        },
    },
    [`weapon_marksmanrifle_mk2`] = {
        itemName = "weapon_marksmanrifle_mk2",
        Name = "Marksman Rifle MK2",
        Components = {
            [1] = {Name = "Extended Clip", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CLIP_02`},
            [2] = {Name = "Holographic Sight", Hash = `COMPONENT_AT_SIGHTS`},
            [3] = {Name = "Large Scope", Hash = `COMPONENT_AT_SCOPE_MEDIUM_MK2`},
            [4] = {Name = "Zoom Scope", Hash = `COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2`},
            [5] = {Name = "Flashlight", Hash = `COMPONENT_AT_AR_FLSH`},
            [6] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP`},
            [7] = {Name = "Flat Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_01`},
            [8] = {Name = "Tactical Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_02`},
            [9] = {Name = "Fat-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_03`},
            [10] = {Name = "Precision Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_04`},
            [11] = {Name = "Heavy Duty Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_05`},
            [12] = {Name = "Slanted Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_06`},
            [13] = {Name = "Split-End Muzzle Brake", Hash = `COMPONENT_AT_MUZZLE_07`},
            [14] = {Name = "Heavy Barrel", Hash = `COMPONENT_AT_MRFL_BARREL_02`},
            [15] = {Name = "Grip", Hash = `COMPONENT_AT_AR_AFGRIP_02`},
            [16] = {Name = "Digital Camo", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO`},
            [17] = {Name = "Brushstroke Camo", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_02`},
            [18] = {Name = "Woodland Camo", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_03`},
            [19] = {Name = "Skull", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_04`},
            [20] = {Name = "Sessanta Nove", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_05`},
            [21] = {Name = "Perseus", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_06`},
            [22] = {Name = "Leopard", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_07`},
            [23] = {Name = "Zebra", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_08`},
            [24] = {Name = "Geometric", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_09`},
            [25] = {Name = "Boom!", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_10`},
            [26] = {Name = "Patriotic", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01`},
            [27] = {Name = "Patriotic 2", Hash = `COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_02`},            
        },
    },
    [`weapon_sniperrifle`] = {
        itemName = "weapon_sniperrifle",
        Name = "Sniper Rifle",
        Components = {
            [1] = {Name = "Suppressor", Hash = `COMPONENT_AT_AR_SUPP_02`},
            [2] = {Name = "Scope", Hash = `COMPONENT_AT_SCOPE_LARGE`},
            [3] = {Name = "Advanced Scope", Hash = `COMPONENT_AT_SCOPE_MAX`},
            [4] = {Name = "Etched Wood Grip Finish", Hash = `COMPONENT_SNIPERRIFLE_VARMOD_LUXE`},
        },  
    },
}